name: Build image then push to registry for deployment

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build-push-imagem-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  arn:aws:iam::989944764342:role/GithubActionsRole
          aws-region: us-east-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Configure Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
     
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Login to DVC
        run: dvc config --global studio.token ${{ secrets.DVC_STUDIO_ACCESS_KEY }}
      
      - name: Adding markdown
        run: echo "### Summary" >> $GITHUB_STEP_SUMMARY

      - name: Model download
        run: dvc artifacts get https://github.com/michelpf/fiap-ds-mlops-laptop-pricing laptop-pricing-india -f
      
      - name: Getting model size
        run: du -h model.pkl | cut -f1 | awk '{print "Model size:", $1}' >> $GITHUB_STEP_SUMMARY

      - name: Tag version download
        run: |
          gto show -r https://github.com/michelpf/fiap-ds-mlops-laptop-pricing --plain | grep 'prod' | awk '{print $3}' > model_version.txt
          gto show -r https://github.com/michelpf/fiap-ds-mlops-laptop-pricing --plain | grep 'prod' | awk '{print "Model Version: " $3}' >  $GITHUB_STEP_SUMMARY

      - name: Unit testing
        run: pytest

      - name: Build image
        run: docker build --platform linux/amd64 -t laptop-pricing-api .
      
      - name: Tag to ECR
        run: docker tag laptop-pricing-api:latest 989944764342.dkr.ecr.us-east-1.amazonaws.com/laptop-pricing-api:latest

      - name: Register in ECR
        run: docker push 989944764342.dkr.ecr.us-east-1.amazonaws.com/laptop-pricing-api:latest

      - name: Update Lambda
        run: aws lambda update-function-code --function-name laptop-pricing-api --image-uri 989944764342.dkr.ecr.us-east-1.amazonaws.com/laptop-pricing-api:latest
